version: '3.0'

volumes:
  tmp:

services:
  backend:
    build: .
    ports:
      - 3000:3000
    networks: [backing-services]
    depends_on:
      - database
      - activemq
    volumes:
      - ./:/usr/src/app
    command: [sh, -c, "./scripts/wait-for-it.sh database:5432 && ./scripts/wait-for-it.sh activemq:61616 -- && if [ -f tmp/pids/server.pid  ]; then rm -f tmp/pids/server.pid; fi && npm start"]

  database:
    image: postgres:9.6.3
    ports: ["5432:5432"]
    networks: [backing-services]
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test

  activemq:
    image: webcenter/activemq:5.14.3
    ports:
      # mqtt
      - "1883:1883"
      # amqp
      - "5672:5672"
      # ui
      - "8161:8161"
      # stomp
      - "61613:61613"
      # ws
      - "61614:61614"
      # jms
      - "61616:61616"
    networks: [backing-services]
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: password
      ACTIVEMQ_WRITE_LOGIN: write
      ACTIVEMQ_WRITE_PASSWORD: password
      ACTIVEMQ_READ_LOGIN: read
      ACTIVEMQ_READ_PASSWORD: password
      ACTIVEMQ_JMX_LOGIN: jmx
      ACTIVEMQ_JMX_PASSWORD: password
      ACTIVEMQ_STATIC_TOPICS: static-topic-1;static-topic-2
      ACTIVEMQ_STATIC_QUEUES: static-queue-1;static-queue-2
      ACTIVEMQ_ENABLED_SCHEDULER: "true"
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048

networks:
  backing-services:
    driver: bridge